
import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Editar() {

    const [data, setData] = useState({
        id: '',
        name: '',
        address: '',
        numero_quartos: '',
        classification: '',
        preco_noite: '',
        disponibilidade: ''
    });

    const [message, setMessage] = useState("");

    const router = useRouter();
    const [id] = useState(router.query.id);

    const getUser = async () => {
        if (id === undefined){
        setMessage("Erro: Hotel nao encontrado!");
        return
        }

        const config = {
            headers: {
                Authorization: `Bearer ${localStorage.getItem('token')}`,
            },
        };
        await axios.get("http://localhost:3000/hotel/" + id, config)
        .then((response) => {
            setData(response.data.hotel);
        }).catch((err) => {
            if (err.response){
                setMessage(err.response.data.mensagem);
            }else{
                setMessage("Erro: Tente mais tarde!");
            }
        });
    }

    useEffect(() => {
        getHotel();
      }, [id]);

      const valueInput = (e) => setData({...data, [e.target.name]: e.target.value});

      const editHotel = async (e) => {
        e.preventDefault();

        const headers = {
            'headers': {
                'Content-Type': 'application/json'
            }
        };
        await axios.put('http://localhost:3000/hotel/', data, headers)
        .then((response) => {
            setMessage(response.data.mensagem);
        }).catch((err) => {
            if (err.response) {
                setMessage(err.response.data.mensagem);
            }else {
                setMessage("Erro: Tente novamente mais tarde ou entre contato com <a href='mailto:a041711@umaia.pt'> Etson Silva ou !");
            }
        });
      }

  return (
    <>
      <Head>
        <title>Sistema de gestão de hoteis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Link href={"/"}><button type="button">Listar</button> </Link>

        <h2>Editar o Hotel</h2>

        {message ? <p>{message}</p> : ""}
        
        <form onSubmit={editHotel}>
            <input type='hidden' name='id' value={data.id} />

            <label>Name:</label>
            <input type='text' name='name' placeholder='Digite o nome' onChange={valueInput} value={data.name}/> <br /><br />
            <label>Endereco:</label>
            <input type='text' name='address' placeholder='Digite o endereço' onChange={valueInput} value={data.address}/> <br /><br />
            <label>Numero de Quartos:</label>
            <input type='text' name='numero_quartos' placeholder='Digite o numero de quartos' onChange={valueInput} value={data.numero_quartos}/> <br /><br />
            <label>Classification:</label>
            <input type='text' name='classification' placeholder='Digite a Classificação' onChange={valueInput} value={data.classification}/> <br /><br />
            <label>Preço por noite:</label>
            <input type='text' name='preco_noite' placeholder='Digite o preço' onChange={valueInput} value={data.preco_noite}/> <br /><br />
            <label>Disponabilidade:</label>
            <input type='text' name='disponibilidade' placeholder='Digite a disponibilidade' onChange={valueInput} value={data.disponibilidade}/> <br /><br />

            <button type='submit'>Guardar Alterações</button>
        </form>
      </main>
    </>
  )
}
