# Use a imagem do Node.js como base
FROM node:14-alpine

# Configura o diretório de trabalho no contêiner
WORKDIR /app

# Copia os arquivos do projeto para o diretório de trabalho
COPY . .

# Instala as dependências do aplicativo
RUN npm install --force

# Build do aplicativo React
RUN npm run build

# Expõe a porta do servidor de desenvolvimento
EXPOSE 3000

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "dev"]
