# Use a imagem do Node.js como base
FROM node:14-alpine

# Configura o diretório de trabalho no contêiner
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copia os arquivos do projeto para o diretório de trabalho

COPY . .

# Build do aplicativo React
#RUN npm run build

# Expõe a porta do servidor de desenvolvimento
EXPOSE 3000

CMD ["npm", "run", "start"]

