
import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useState } from 'react';

export default function Editar() {

    const [data, setData] = useState({
        id: '',
        name: '',
        email: ''
    });

    const [message, setMessage] = useState("");

    const router = userRouter();
    useState(router.query.id);
    console.log(router.query.id);

    const getUser = async () => {
        if (id === undefined){
        setMessage("Erro: Usuario nao encontrado!");
        return
        }
        await axios.get("http://localhost:3000/usuario/" + id)
        .then((response) => {

        }).catch((err) => {
            if (err.response){

            }else{
                setMessage("Erro: Tente mais tarde!")
            }
        });
    }
  return (
    <>
      <Head>
        <title>Sistema de gestão de hoteis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Link href={"/"}><button type="button">Listar</button> </Link>

        <h2>Editar o Usuario</h2>

        {message ? <p>{message}</p> : ""}

      </main>
    </>
  )
}
