import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Visualizar() {

  //Declarar a variavel para receber os registros retornado da API
  const [data, setData] = useState([]);

  //Declarar a variavel para receber a mensagen
  const [message, setMessage] = useState("");

  //Receber o parametro enviado na URL
  const router = useRouter();
  //console.log(router.query.id);
  const [id] = useState(router.query.id);

  const getQuarto = useCallback(async () => {
    if (id === undefined) {
      setMessage("Erro: Quarto não encontrado!");
      return;
    }
  
    const config = {
      headers: {
        Authorization: `Bearer ${localStorage.getItem('token')}`, 
      },
    };
    try {
      const response = await axios.get("http://localhost:3000/quarto/" + id, config);
      console.log(response.data.quarto);
      setData(response.data.quarto);
    } catch (err) {
      if (err.response) {
        setMessage(err.response.data.mensagen);
      } else {
        setMessage("Erro: Tente mais tarde!");
      }
    }
  }, [id]);
  

  useEffect(() => {
    getQuarto();
  }, [id, getQuarto]);

  return (
    <>
      <Head>
        <title>Sistema de gestão de hoteis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Link href={"/"}><button type="button">Listar</button> </Link>{" "}
        <Link href={`/editar/${data.id}`}> <button type="button">Editar</button></Link>{" "}

        <h2>Detalhes do Quarto</h2>

        {message ? <p>{message}</p> : ""}

        <span>ID: {data.id}</span><br />
        <span>Numero: {data.numero_quarto}</span><br />
        <span>Disponibilidade: {data.disponibilidade}</span><br />

      </main>
    </>
  );
}
