import Head from 'next/head';
import { useEffect, useState } from 'react';
//Biblioteca para conectar com a api
import axios from 'axios';
import Link from 'next/link';

export default function Home() {
  const [data, setData] = useState([]);
  const [message, setMessage] = useState('');

  useEffect(() => {
    const fetchUsuarios = async () => {
      try {
        const response = await axios.get('http://localhost:3000/usuario', {
          headers: {
            Authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjg3NzU3MDkxLCJleHAiOjE2ODc3NjA2OTF9.YTSNW7AyMosdpY1-I1JkTA4VKldzsJlc6ibNYK9HbNY', // Substitua pelo seu token válido
          },
        });

        setData(response.data.usuario);
      } catch (error) {
        if (error.response) {
          setMessage(error.response.data.mensagem);
        } else {
          setMessage("Erro: Tente novamente mais tarde!");
        }
      }
    }

    fetchUsuarios();
  }, []);

  return (
    <>
      <Head>
        <title>Sistema de gestão de hoteis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Link href={"/cadastrar"}><button type="button">Cadastrar</button> </Link>
        <Link href={"/login"}><button type="button">Login</button> </Link>
        <h2>Listar Usuarios</h2>

       {message ? <p>{message}</p> : ""}
       <Link href={`/visualizar/5`}> <button type="button">Visualizar</button></Link>{" "}
       {data.map(usuario => (
        <div key={usuario.id}>
          <span>ID: {usuario.id}</span><br />
          <span>Nome: {usuario.name}</span><br />
          <span>E-mail: {usuario.email}</span><br />
          <Link href={`/visualizar/${usuario.id}`}> <button type="button">Visualizar</button></Link>{" "}
          <hr />
        </div>
       ))}

       <br />
       <br />
       <br />
       <br />
      </main>
    </>
  )
}
