import Head from 'next/head';
import { useEffect, useState } from 'react';
//Biblioteca para conectar com a api
import axios from 'axios';
import Link from 'next/link';
import { serviceDelete } from './service/serviceDelete';

export default function Home() {
  const [data, setData] = useState([]);
  const [message, setMessage] = useState('');


  const fetchUsuarios = async () => {
    try {
      const response = await axios.get('http://localhost:3000/hotel');

      setData(response.data.hotel);
    } catch (error) {
      if (error.response) {
        setMessage(error.response.data.mensagem);
      } else {
        setMessage("Erro: Tente novamente mais tarde!");
      }
    }
  };
  useEffect(() => {
    fetchUsuarios();
  }, []);

  const deleteUser = async (hotelid) => {
    console.log(hotelid);
    const response = await serviceDelete('http://localhost:3000/hotel' + hotelid);
    setMessage(response);
    fetchUsuarios();
  };

  return (
    <>
      <Head>
        <title>Sistema de gestão de hoteis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Link href={"/cadastrar"}><button type="button">Cadastrar</button> </Link>
        <Link href={"/login"}><button type="button">Login</button> </Link>
        <Link href={"/"}><button type="button">usuario</button> </Link>
        <Link href={"/listar_hotel"}><button type="button">hotel</button> </Link>
        <Link href={"/listar_quartos"}><button type="button">quartos</button> </Link>
        <Link href={"/listar_reserva"}><button type="button">reserva</button> </Link>
        <h2>Listar hotel</h2>

        {message ? <p>{message}</p> : ""}
        {data.map(hotel => (
          <div key={hotel.id}>
            <span>ID: {hotel.id}</span><br />
            <span>Nome: {hotel.name}</span><br />
            <span>address: {hotel.address}</span><br />
            <span>numero_quartos: {hotel.numero_quartos}</span><br />
            <span>classification: {hotel.classification}</span><br />
            <span>preco_noite {hotel.preco_noite}</span><br />
            <span>disponibilidade {hotel.disponibilidade}</span><br />
            <Link href={`/visualizar/${hotel.id}`}> <button type="button">Visualizar</button></Link>{" "}
            <Link href={`/editar/${hotel.id}`}> <button type="button">Editar</button></Link>{" "}
            <button type="button" onClick={()=> deleteUser(hotel.id)}>Apagar</button>{" "}
            <hr />
          </div>
        ))}

        <br />
        <br />
        <br />
        <br />
      </main>
    </>
  )
}