import Head from 'next/head';
import { useEffect, useState } from 'react';
//Biblioteca para conectar com a api
import axios from 'axios';
import Link from 'next/link';
import { serviceDelete } from './service/serviceDelete';

export default function Home() {
  const [data, setData] = useState([]);
  const [message, setMessage] = useState('');


  const fetchHotel = async () => {
    try {
      const response = await axios.get('http://localhost:3000/hotel',{
        headers: {
          Authorization: `Bearer ${localStorage.getItem('token')}`,
        },
      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
      setData(response.data.hotel);
    } catch (error) {
      if (error.response) {
        setMessage(error.response.data.mensagem);                                                                                                                                                                                                                                                                    
      } else {
        setMessage("Erro: Tente novamente mais tarde!");
      }
    }
  };                                                                                                                                                                                                              
  useEffect(() => {
    fetchHotel();
  }, []);

  const deleteHotel = async (hotelsid) => {                                                                                                           
    console.log(hotelsid);
    const response = await serviceDelete('http://localhost:3000/hotel' + hotelsid);
    setMessage(response);
    fetchHotel();
  };

  return (                                                                                   
    <>                                                                                                                                                                                                                                                                                                                                     
      <Head>
        <title>Sistema de gestão de hoteis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Link href={"./criar"}><button type="button">Criar Hotel</button> </Link>
        <Link href={"../login"}><button type="button">Login</button> </Link>
        <Link href={"../"}><button type="button">Usuario</button> </Link>
        <Link href={"../Quarto/listar_quartos"}><button type="button">Quartos</button> </Link>
        <Link href={"../Reserva/listar_reserva"}><button type="button">Reserva</button> </Link>
        <h2>Listar hotel</h2>

        {message ? <p>{message}</p> : ""}
<<<<<<< HEAD
        {data.map(hotels => (
          <div key={hotels.id}>
            <span>ID: {hotels.id}</span><br />
            <span>nome: {hotels.nome}</span><br />
            <span>address: {hotels.address}</span><br />
            <span>numero_quartos: {hotels.numero_quartos}</span><br />
            <span>classification: {hotels.classification}</span><br />
            <span>preco_noite {hotels.preco_noite}</span><br />
            <span>disponibilidade {hotels.disponibilidade}</span><br />
            <Link href={`/visualizar/${hotels.id}`}> <button type="button">Visualizar</button></Link>{" "}
            <Link href={`/editar/${hotels.id}`}> <button type="button">Editar</button></Link>{" "}
            <button type="button" onClick={()=> deleteHotel(hotels.id)}>Apagar</button>{" "}
=======
        {data.map(hotel => (
          <div key={hotel.id}>
            <span>ID: {hotel.id}</span><br />
            <span>nome: {hotel.nome}</span><br />
            <span>address: {hotel.address}</span><br />
            <span>numero_quartos: {hotel.numero_quartos}</span><br />
            <span>classification: {hotel.classification}</span><br />
            <span>preco_noite {hotel.preco_noite}</span><br />
            <span>disponibilidade {hotel.disponibilidade}</span><br />
            <Link href={`/visualizar/${hotel.id}`}> <button type="button">Visualizar</button></Link>{" "}
            <Link href={`/editar/${hotel.id}`}> <button type="button">Editar</button></Link>{" "}
            <button type="button" onClick={()=> serviceDelete(hotel.id)}>Apagar</button>{" "}
>>>>>>> a1152b0f2c6ee207e9b3f0ee893d8b9a51d258ac
            <hr />
          </div>
        ))}

        <br />
        <br />
        <br />
        <br />
      </main>
    </>
  )
}