import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Visualizar() {

  //Declarar a variavel para receber os registros retornado da API
  const [data, setData] = useState([]);

  //Declarar a variavel para receber a mensagen
  const [message, setMessage] = useState("");

  //Receber o parametro enviado na URL
  const router = useRouter();
  //console.log(router.query.id);
  const [id] = useState(router.query.id);

  const getReserva = useCallback(async () => {
    if (id === undefined) {
      setMessage("Erro: Reserva não encontrada!");
      return;
    }
  
    const config = {
      headers: {
        Authorization: `Bearer ${localStorage.getItem('token')}`, 
      },
    };
    try {
      const response = await axios.get("http://localhost:3000/reserva/" + id, config);
      console.log(response.data.reserva);
      setData(response.data.reserva);
    } catch (err) {
      if (err.response) {
        setMessage(err.response.data.mensagen);
      } else {
        setMessage("Erro: Tente mais tarde!");
      }
    }
  }, [id]);
  

  // useEffect é usado para lidar com efeitos colaterais em um componente.
  // Por exemplo, atualizar o estado do componente, fazer chamadas a APIs, manipular eventos, entre outros.
  useEffect(() => {
    getReserva();
  }, [id, getReserva]);

  return (
    <>
      <Head>
        <title>Sistema de gestão de hoteis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={"/"}><button type="button">Listar</button> </Link>{" "}
        <Link href={`/editar/${data.id}`}> <button type="button">Editar</button></Link>{" "}

        <h2>Detalhes da Reserva</h2>

        {message ? <p>{message}</p> : ""}

        <span>ID: {data.id}</span><br />
        <span>Data Check-In: {data.data_check_in}</span><br />
        <span>Status da Reserva: {data.status_reserva}</span><br />
      </main>
    </>
  )
}
