import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Visualizar() {
  const [data, setData] = useState([]);
  const [message, setMessage] = useState('');

  const router = useRouter();
  const [id] = useState(router.query.id);

  const getHotel = async () => {
    if (id === undefined) {
      setMessage("Erro: Hotel não encontrado!");
      return;
    }
  
    const config = {
      headers: {
        Authorization: `Bearer ${localStorage.getItem('token')}`, 
      },
    };

    await axios.get("http://localhost:3000/hotel/" + id, config)
      .then((response) => {
        console.log(response.data.hotels);
        //Atribuir o registro no state data

        setData(response.data.hotels);
      }).catch((err) => {//Acessa o catch quando a API retornar erro
        //Acessa ao IF quando a API retornar erro
        if (err.response) {
          //Atribuir a mensagen no state message
          setMessage(err.response.data.mensagen);
        } else {
          //Atribuir a mensagen no state message
          setMessage("Erro: Tente mais tarde!");
        }
      });

  // useEffect é usado para lidar com efeitos colaterais e um componente.
  //Por exemplo, ataulizar o estado do componente, fazer chamadas a APIs, manipular eventos, entre outros
    try {
      const response = await axios.get("http://localhost:3000/hotel/" + id, config);
      console.log(response.data.hotel);
      setData(response.data.hotel);
    } catch (err) {
      if (err.response) {
        setMessage(err.response.data.mensagen);
      } else {
        setMessage("Erro: Tente mais tarde!");
      },
    }
  }
  
  useEffect(() => {
    getHotel();
  }, [id, getHotel]);

  return (
    <>
      <Head>
        <title>Sistema de gestão de hotéis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={'/'}><button type="button">Listar</button></Link>{' '}
        <Link href={`/editar/${data.id}`}><button type="button">Editar</button></Link>{' '}

        <h2>Detalhes do Hotel</h2>

        {message ? <p>{message}</p> : ''}

        <span>ID: {data.id}</span><br />
        <span>Name: {data.name}</span><br />
        <span>Endereço: {data.address}</span><br />
      </main>
    </>
  );
}
